### ISSUE TITLE
除了直播以外的其他功能貌似Failed了

### ISSUE THREAD

**Issue by MostlyHarmlessxyz** [endcloud/bbhouse-tauri#11]
是接口换了还是？
反正这边只剩直播视频流能看了
不着急，目前能看直播也挺好的了，比哔哩哔哩那个傻13网页端直播间好多了

**Comment by endcloud** [comment]
感谢反馈。
12 月的时候 b 站全站接口基本都更新了一遍，导致很多第三方都是半残废的状态，我抓到几个新的 api 正在测试。加上在做项目结构的重构，时间管理有点灾难，一周内/新年时预计会发新版。

**Comment by MostlyHarmlessxyz** [comment]
> 感谢反馈。
> 12 月的时候 b 站全站接口基本都更新了一遍，导致很多第三方都是半残废的状态，我抓到几个新的 api 正在测试。加上在做项目结构的重构，时间管理有点灾难，一周内/新年时预计会发新版。

不着急的，加油！很感谢能做一款mac上轻便好用的客户端❤️
