### ISSUE TITLE
能在下个版本编译一个Macos_arm版本的吗？

### ISSUE THREAD

**Issue by MostlyHarmlessxyz** [endcloud/bbhouse-tauri#3]
十分感谢.

**Comment by endcloud** [comment]
> 十分感谢.

非常感谢你的建议. 

但很抱歉, 没有办法做到.

tauri使用的技术非常依赖OS的原生API,  无法进行任何形式的交叉编译.
本项目的多平台`release`还是依赖`Github Action`

不过Mac下编译环境的安装非常简单, 我的Intel Mac编译时间也并不太长.

过两天下个版本发布时, 我会同步发布一期Mac下部署的详细document.

希望能帮助到你. :)

**Comment by endcloud** [comment]
> 十分感谢.

更新（/doge），最新release的v1.1.0中已经有了aarch64的版本，
感谢你的提议，让我落实了长久以来更换M1 Macbook的想法，真是太爽啦。

**Comment by MostlyHarmlessxyz** [comment]
> > 十分感谢.
> 
> 更新（/doge），最新release的v1.1.0中已经有了aarch64的版本， 感谢你的提议，让我落实了长久以来更换M1 Macbook的想法，真是太爽啦。

哈哈哈哈哈，谢谢啦。M1确实爽的，我已经不大习惯风扇声音了
（😂
